#!/bin/bash

function calculator(){
options=("Add" "Subtract" "Multiply" "Divide" "Power of" "Modulos" "Exit")

echo "Select an option:"

select opt in "${options[@]}"
do
    case $opt in
        "Add")
            echo "You chose to add"
            add
            is_odd_even
            is_prime
            is_div_by_five
            ;;
        "Subtract")
            echo "You chose to subtract"
            substract
            is_odd_even
            is_prime
            is_div_by_five
            ;;
        "Multiply")
            echo "You chose to multiply"
            multiply
            is_odd_even
            is_prime
            is_div_by_five
            ;;
        "Divide")
            echo "You chose to divide"
            dividing
            is_odd_even
            is_prime
            is_div_by_five
            ;;
        "Power of")
            echo "You chose to calculate power of"
            power_of
            is_odd_even
            is_prime
            is_div_by_five
            ;;
        "Modulos")
            echo "You chose to calculate modulos"
           modulos
           is_odd_even
           is_prime
           is_div_by_five
            ;;
        "Exit")
            echo "Exiting..."
            break
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
done
}
function add()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val+"
   length=$((length-1))
   fi
   
done

sum=0
for val in "${args[@]}"; do
    sum=$((sum + val))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}
function substract()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^-?[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val-"
   length=$((length-1))
   fi
   
done
length=${#args[@]}
((sum=${args[0]}))
for ((i = 1; i < $length; i++)); do
            ((sum -= args[i]))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}


function multiply()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^-?[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val*"
   length=$((length-1))
   fi
   
done
length=${#args[@]}
((sum=${args[0]}))
for ((i = 1; i < $length; i++)); do
            sum=$((sum * args[i]))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}


function dividing()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^-?[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val/"
   length=$((length-1))
   fi
   
done
length=${#args[@]}
((sum=${args[0]}))
for ((i = 1; i < $length; i++)); do
            sum=$((sum / args[i]))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}

function power_of()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^-?[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val^"
   length=$((length-1))
   fi
   
done
length=${#args[@]}
((sum=${args[0]}))
for ((i = 1; i < $length; i++)); do
            sum=$((sum ** args[i]))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}
function modulos()
{
    echo "Enter values separated by spaces (press Enter after entering all values):"
declare -a args
read -a args
length=${#args[@]}
flag=0
for val1 in "${args[@]}"; do
if [[ $val1 =~ ^-?[0-9]+$ ]] 
   then :
   else flag=1
   break
   fi
   done
   if((flag==0))
   then echo "You entered the following values:"
for val in "${args[@]}"; do
if ((length==1)) 
    then echo -n "$val"
    else
    echo -n "$val%"
   length=$((length-1))
   fi
   
done
length=${#args[@]}
((sum=${args[0]}))
for ((i = 1; i < $length; i++)); do
            sum=$((sum % args[i]))
done
echo ""
echo "The sum of the numbers is: $sum"
else echo "You have entered an input that is not a number at least once"
fi
}

function is_odd_even(){
    if(($sum%2==0))
    then echo "answer is even"
    else echo "answer is odd"
    fi
}

function is_prime(){

    flag=0
    i=0
    if((sum == 2 || sum == 3))
    then echo The number is prime
    flag=1
    fi
    while(($flag==0))
    do
    i=$((i+1))
    if((6*i+1 == $sum || 6*i-1 == $sum))
    then echo The number is prime
    flag=1
    elif((6*i+1 > $sum && 6*i-1 > $sum))
    then echo The number is not prime
    flag=1
    fi
    done
}

function is_div_by_five(){
    if(($sum%5==0))
    then echo "the number is dividable by 5"
    else echo "the number is not dividable by 5"
    fi
}

calculator